### ISSUE TITLE
Command to end match

### ISSUE THREAD

**Issue by ghostrider-05** [blaku-rl/MapExpansionPlugin#1]
I don't know if it's possible with bakkesmod but opened this issue in case it's possible.

A command to end a match / assign a winner to a match by checking a bool variable to check if the value is true every tick or maybe something with kismet events?

**Comment by blaku-rl** [comment]
Just added the ability to end the match via a command. You can also change the score for individual teams by the change score command. I'll close the issue once the plugin is approved on bakkesmod plugins.

**Comment by blaku-rl** [comment]
It's now possible with this command ```gamestate end```
